ACS-2234: Handle 412 error code from WebscriptException
Alfresco/surf-webscripts pull request #135
Opened 2022-01-07 10:18 UTC by mpichura

In community-repo when `ArchivedIOException` (content is archived) is caught when executing webscript, then it is re-thrown as `WebscriptException `with error code 412. 
To minimize log pollution, full stack trace will be logged only when debug enabled.

2022-01-07 10:45 UTC, PunchedChimera reviewed
Looks good so far. I can approve once out of draft 👍

2022-01-07 10:45 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +        final Map<Integer, String> handledExecuteScriptErrorCodes = Map.of(
This might as well be declared as a constant.

2022-01-07 10:47 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +        if (throwable instanceof WebScriptException && (handledExecuteScriptErrorCodes.keySet().contains(((WebScriptException) throwable).getStatus())))
You can use `containsKey` rather than `keySet().contains`

2022-01-07 10:50 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +                if (debug)
Duplicate check for debug (see outer if statement).

2022-01-07 10:54 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +            else // handle ArchivedIOException to lower log pollution
I don't think that this comment matches the logic.  In this else we're handling two things:
* debug == false
* HttpServletResponse.SC_PRECONDITION_FAILED
Is the second of these the same as "ArchivedIOException"??

2022-01-07 10:55 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +                if (debug) { // log with stack trace at debug level
[Formatting] Trailing brace.

2022-01-07 10:57 UTC, tpage-alfresco requested changes
Something about the conditional logic looked a bit weird to me.

2022-01-10 09:25 UTC, mpichura commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +        final Map<Integer, String> handledExecuteScriptErrorCodes = Map.of(
I had that in constant at first go but then realized it looks less readable (to me at least - it's used only in this place and you'd need to go to the top of the class to see the codes). 
I am happy to change it to constant if above is not convincing enough ;)

2022-01-10 09:26 UTC, mpichura commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +        if (throwable instanceof WebScriptException && (handledExecuteScriptErrorCodes.keySet().contains(((WebScriptException) throwable).getStatus())))
Thanks switched to `containsKey`.

2022-01-10 09:27 UTC, mpichura commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +                if (debug)
Thanks. I changed the outer condition as check for `debug` was not necessary there.

2022-01-10 10:24 UTC, mpichura commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +            else // handle ArchivedIOException to lower log pollution
After changing the preceding if condition, now this comment (slightly changed) matches the logic. 
However, I started to think about more general log message for 412 error code (I assume `executeScript` could be called from a place other than community-repo where we map `ArchivedIOException` to 412 error code) - thus changed that too.

2022-01-10 10:25 UTC, mpichura commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +                if (debug) { // log with stack trace at debug level
Thanks, re-formatted.

2022-01-11 13:25 UTC, tpage-alfresco commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/AbstractRuntime.java
> +        final Map<Integer, String> handledExecuteScriptErrorCodes = Map.of(
I guess the overhead of redeclaring this as a local variable each method call is pretty small, so I think it's fine to have it like this.

2022-01-11 13:30 UTC, tpage-alfresco approved these changes
LGTM

2022-01-11 13:44 UTC, PunchedChimera approved these changes

2022-01-11 13:54 UTC, tiagosalvado10 approved these changes

2022-01-13 09:51 UTC, merged