Feature/apps 1794 migration to gha
Alfresco/surf-webscripts pull request #142
Opened 2022-12-28 11:26 UTC by omkaryadv177

migration of travis to github action

2023-01-11 14:45 UTC, kavitshah-gl requested changes

2023-01-11 14:45 UTC, kavitshah-gl commented on .github/workflows/build.yml
> +    if: ${{ ( !contains(github.event.head_commit.message, '[no-release]')  ) && ( github.ref_name == 'master' || startsWith(github.ref_name, 'support/')) }}
fork check should be placed?

2023-01-14 10:36 UTC, kavitshah-gl approved these changes
Looks fine now

2023-01-16 05:06 UTC, MohinishSah approved these changes

2023-01-16 05:12 UTC, merged