WIP: MNT-22154 : [Security] Share proxy allows unauthenticated access to repository webscripts
Alfresco/surf-webscripts pull request #99
Opened 2021-02-11 12:56 UTC by alexbalmus

- [WIP] suggested fix to protect SOLR endpoint

2021-02-11 13:05 UTC, alexbalmus commented
This is still WIP. There's also a change required on Share side in slingshot-application-context.xml:

`    <bean id="endpointController" class="org.springframework.extensions.webscripts.servlet.mvc.EndPointProxyController">
        <property name="cacheSeconds" value="-1"/>
        <property name="useExpiresHeader">
            <value>true</value>
        </property>
        <property name="useCacheControlHeader">
            <value>true</value>
        </property>
        <property name="configService" ref="web.config"/>
        <property name="connectorService" ref="connector.service"/>
        <property name="supportedMethods">
            <null/>
        </property>
        <property name="proxyControllerInterceptor" ref="slingshotProxyControllerInterceptor"/>
        <property name="forbiddenPattern" value="^.*/api/solr/.*$" />
    </bean>`

Things to take care of:

1. That "forbiddenPattern" property should probably be a list of strings
2. More checks are needed (as required by David) like defense against certain kind of injections.
3. David required returning 403 if not allowed; In the code though I've seen the practice of throwing a WebScriptsPlatformException which results in a 500 (Internal Server Error) response; not sure how forcing a specific response is handled at WebScripts level.
4. Consider a "friendlier" way of specifying those patterns, as opposed to editing that Spring context XML file
5. More testing will be needed to detect possible side effects.

2021-02-11 13:06 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +    private String forbiddenPattern;
This should probably be a List<String>.

2021-02-11 13:09 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            throw new WebScriptsPlatformException("Forbidden URI pattern: " + forbiddenPattern);
This results in 500 Internal Server Error (and a web page that's not very informative: "Something's wrong with this page..."). TODO: How to return a 403 and also provide a nicer user experience?

2021-02-11 13:20 UTC, araschitor commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            throw new WebScriptsPlatformException("Forbidden URI pattern: " + forbiddenPattern);
You could use
throw new WebScriptsPlatformException("Forbidden URI pattern: ".concat(forbiddenPattern);

2021-02-11 20:11 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            throw new WebScriptsPlatformException("Forbidden URI pattern: " + forbiddenPattern);
I'd rather not :)

2021-02-14 22:37 UTC, pieCit87 reviewed
about the load of those properties in share, i imagine that I have 2 properties inside (or a specific file or the global.prop file) done like this:
alfresco.proxy.whitelist=patternA,patternB,patternC (considering the ',' as splitter)
alfresco.proxy.blacklist=patternD,patternE,patternC (considering the ',' as splitter)

2021-02-14 22:37 UTC, pieCit87 commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +    private List<String> uriWhitelist = Collections.singletonList("^.*$");
I think here we should ask a brian review to avoid misunderstanding about how to initialize by default.I don't remember if was expressed as desiderata.

2021-02-14 22:37 UTC, pieCit87 commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        throw new WebScriptsPlatformException("Invalid URI: " + uri);
is this approach helping the user experience?
res.setStatus(HttpServletResponse.SC_UNAUTHORIZED,
                        "No USER_ID found in session and requested endpoint requires authentication.");
                
                // no further processing as authentication is required but not provided
                return null;

2021-02-14 22:37 UTC, pieCit87 commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        // TODO: perform additional sanitization to prevent header injection, request splitting etc.
We can speak with David @DavidCervigni  in order to see what do to here

2021-02-14 22:37 UTC, pieCit87 commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            for (String forbiddenPattern : uriBlacklist)
Is also possible here to be raised a performance issue. Imagining a real productive env with several patterns to match.

2021-02-15 08:21 UTC, DavidCervigni commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        // TODO: perform additional sanitization to prevent header injection, request splitting etc.
Hi, this example shows canonicalization solves many issues, after canonicalization we should check only expected alphanumeric / and .  chars are in the path element[/, A-z-0-9,.] (anything else) , the example below shows also new line injection (likely to result in a header injection (so no new lines allowed after canonicalization)

            System.out.println((new java.net.URI("https://www.example.com/%73olr/path/../%61pi%2F00/1%0A/2")).normalize().getPath());
gives:
/solr/api/00/1
/2

2021-02-15 08:25 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            for (String forbiddenPattern : uriBlacklist)
No sure what the alternative could be though.

2021-02-15 08:25 UTC, DavidCervigni commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            for (String forbiddenPattern : uriBlacklist)
This is a legit concern, if the matcher is optimized/compiled the performance should be negligible. I saw 100s rules applied per request in systems like mod_security ruleset. btw those are. generic rules to protect Java-based attacks:
https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf

2021-02-15 08:27 UTC, DavidCervigni commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +                    return true;
If we match a forbidden pattern (plausible attack) we should log a warning with some request info.

2021-02-15 10:23 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        throw new WebScriptsPlatformException("Invalid URI: " + uri);
I've tried res.setStatus(HttpServletResponse.SC_UNAUTHORIZED, "...") (and then return null instead of throwing exception) but this does not seem to help here (I'm just taken to an empty page). 

However, I've found res.sendError(HttpServletResponse.SC_UNAUTHORIZED, "") which does the job by displaying an Apache Tomcat error page with the message. I'll do another commit with this shortly.

2021-02-15 12:07 UTC, skopf commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +            for (String forbiddenPattern : uriBlacklist)
Yes, but this code compiles the pattern each time. It would be more performant to have a precompiled
List<Pattern> uriWhitelist
and then just match tem

2021-02-15 12:09 UTC, skopf commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        uri = (new java.net.URI(uri)).normalize().getPath();
I don't understand this line. What does the variable "uri" contain? The URI or just the path ?
You are trying to read the content of this string as a URI, but then you are just extracting the path out of it

2021-02-15 13:12 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +    private List<String> uriWhitelist = Collections.singletonList("^.*$");
The rationale behind this initialization (allow all by default) is because we don't want to break existing behavior. Moreover, the Webscripts component is also used by Repo.

2021-02-15 13:18 UTC, alexbalmus commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +        uri = (new java.net.URI(uri)).normalize().getPath();
uri contains something like "alfresco-noauth/api/solr/aclchangesets" (the whole URL being "http://localhost:8181/share/proxy/alfresco-noauth/api/solr/aclchangesets?fromId=1").

2021-02-16 10:32 UTC, skopf requested changes
See inline comment. By default, we need to block SOLR at least.

2021-02-16 10:32 UTC, skopf commented on spring-webscripts/spring-webscripts/src/main/java/org/springframework/extensions/webscripts/servlet/mvc/EndPointProxyController.java
> +    private List<Pattern> uriPatternsBlacklist;
I think by default we should have the SOLR endpoints on this list.

2021-02-17 11:24 UTC, skopf approved these changes

2021-02-17 13:40 UTC, pieCit87 approved these changes
LGTM

2021-02-17 13:44 UTC, bogdanbocancea approved these changes

2021-02-17 16:15 UTC, merged